{"name": "Проверка неуспешного логина для существующего курьера - неверный пароль", "status": "passed", "start": 1730235331907, "stop": 1730235331984, "uuid": "46616e48-6cd4-4f26-a757-ea872ca67d40", "historyId": "7cd374426efd7726af47f03ea2494608", "testCaseId": "7cd374426efd7726af47f03ea2494608", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_cant_login_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "15252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}